theme: jekyll-theme-minimal
title: marrubio homepage
description: Bookmark this to keep an eye on my project updates!
# Main navigation links shown in the site header
nav:
	- title: Home
		url: /
	- title: About
		url: /about/
	- title: Projects
		url: /projects/
	- title: Contact
		url: /contact/